---

- name: Install aptitude
  become: true
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Install required system packages
  become: true
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  become: true
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Install packages
  become: true
  apt:
    name: ['python3', 'python3-pip']
    state: latest
    update_cache: true

- name: Upgrade pip
  become: true
  pip:
    name: ['pip']
    state: latest

- name: Install Python packages
  become: true
  pip:
    name: ['docker', 'jsondiff', 'docker', 'pyyaml', 'docker-compose']
    state: latest

- name: Leave swarm
  become: true
  community.docker.docker_swarm:
    state: absent
    force: true
  register: result

- name: Restarted docker
  become: true
  ansible.builtin.systemd:
    name: docker
    state: restarted
  register: result

- name: Prune everything (including non-dangling images)
  become: true
  community.docker.docker_prune:
    containers: true
    images: true
    images_filters:
      dangling: false
    networks: true
    volumes: true
    builder_cache: true

- name: ext4 /dev/vdb
  become: true
  community.general.filesystem:
    fstype: ext4
    dev: /dev/vdb

- name: Mount
  become: true
  ansible.posix.mount:
    path: /var/lib/docker/volumes
    src: /dev/vdb
    fstype: ext4
    state: mounted

- name: Restart docker daemon
  become: true
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: docker

- name: Sleep for 15 seconds and continue with play
  ansible.builtin.wait_for:
    timeout: 15
  delegate_to: localhost